baseurl = "http://robertbasic.com/"
languageCode = "en-us"
title = "Robert Basic's blog"
theme = "robertbasic.com"

pygmentsstyle = "monokai"

[params]
    description = "Robert Basic is a web developer from Serbia."


[taxonomies]
    tag = "tags"
    category = "categories"
