baseurl = "https://robertbasic.com/"
languageCode = "en-us"
title = "Robert Basic, software engineer, consultant"
theme = "robertbasic.com"

pygmentsstyle = "monokai"
pygmentscodefences = "true"

[permalinks]
    blog = "/:section/:slug/"
    static = "/:filename/"

[params]
    description = "Robert Basic is a software engineer, consultant, and open source contributor."


[taxonomies]
    tag = "tags"
    category = "categories"
    2018 = "2018"
    2017 = "2017"
    2016 = "2016"
    2015 = "2015"
    2014 = "2014"
    2013 = "2013"
    2012 = "2012"
    2011 = "2011"
    2010 = "2010"
    2009 = "2009"
    2008 = "2008"
